### ISSUE TITLE
Could you use a m5stack atom (ESP32) for HyperSPI

### ISSUE THREAD

**Issue by Bascht74** [awawa-dev/HyperSPI#11]
Hi, 

I want to switch to the SPI-Version and I am looking for a nice setup. 

I found the m5stack atom ( https://shop.m5stack.com/collections/m5-controllers/products/atom-lite-esp32-development-kit )
that has:
GPIO19 -> MOSI
GPIO23 -> CLK
CPIO33 -> MISO
according to https://static-cdn.m5stack.com/resource/docs/products/core/atom_lite/atom_lite_map_01.webp
but no "native" SPI Chip Select. But you said that it is needed for the ESP32 version.

There is a nice prototyping board with cover available:
https://shop.m5stack.com/products/atom-hub-proto-kit

If I could use another GPIO, e.g. 22 for SPI CS, I could set it up and switch to SPI and nicely power the device via my PI4 with 5V...
Then I could use GPIO23 and GPIO25 for two LED segments (and level shift them to 5V), if a second segment becomes available for the SPI version, too (I hope so).

So my two questions are: 
1. Will you provide the "new" ESP32 V.8.00 for the SPI-Version as well in the future?
2. Can I use another available GPIO22/GPIO23/GPIO25 for that? E.G. GPIO19 MOSI, GPIO23 CLK, GPIO33 MISO, CPIO22 CS, GPIO23 first segment, GPIO25 second segment (SK6812 LEDS)

Thx for those hints and merry Chrismas!

Seb

**Comment by awawa-dev** [comment]
> Hi,
> 
> I want to switch to the SPI-Version and I am looking for a nice setup.
> 
> I found the m5stack atom ( https://shop.m5stack.com/collections/m5-controllers/products/atom-lite-esp32-development-kit ) that has: GPIO19 -> MOSI GPIO23 -> CLK CPIO33 -> MISO according to https://static-cdn.m5stack.com/resource/docs/products/core/atom_lite/atom_lite_map_01.webp but no "native" SPI Chip Select. But you said that it is needed for the ESP32 version.

Hi
That's right: it was needed for my ESP32 board (Esp8266 doesn't need it). 

> 
> There is a nice prototyping board with cover available: https://shop.m5stack.com/products/atom-hub-proto-kit
> 
> If I could use another GPIO, e.g. 22 for SPI CS, I could set it up and switch to SPI and nicely power the device via my PI4 with 5V... Then I could use GPIO23 and GPIO25 for two LED segments (and level shift them to 5V), if a second segment becomes available for the SPI version, too (I hope so).
> 
> So my two questions are:
> 
>     1. Will you provide the "new" ESP32 V.8.00 for the SPI-Version as well in the future?
> 
>     2. Can I use another available GPIO22/GPIO23/GPIO25 for that? E.G. GPIO19 MOSI, GPIO23 CLK, GPIO33 MISO, CPIO22 CS, GPIO23 first segment, GPIO25 second segment (SK6812 LEDS)
> 
> 
> Thx for those hints and merry Chrismas!
> 
> Seb

1. Of course there will be a version upgraded to platformio and offering multisegments. It will be based on HyperSerialESP32, but its evolution is not finished yet. I plan one more important feature for HyperSerialESP32 and then new version of HyperSPI will be released. Don't know ETA because it requires a bit of research.

2. Usually ESP32 allows pin remapping. But when we come into details there are exceptions. For example to have VSPI interface working on very high speeds you can't use other than default pinouts because it won't work (GPIO matrix 40MHz limitation) , so I don't know if there are more surprises and can't guarantee the result. Theoretically it should work if you board **has two i2s interfaces** available for multisegment (or at least one and hope that I will succeed with my researcher).

**Comment by Bascht74** [comment]
Thx for the infos. I will try if the new version ist ready!

**Comment by awawa-dev** [comment]
Hi
Version has been updated and is ready for testing: https://github.com/awawa-dev/HyperSPI/pull/13
HyperSPI was migrated to platformio. Can be compiled online using following manual: https://github.com/awawa-dev/HyperSPI/wiki
